cargo-features = ["edition2021"]

[package]
name = "blake3-file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.41"
blake3 = {version="0.3.8",features=["rayon"]}
